const products = [
    {
        id: 0,
        title: 'Crispy',
        price: '450',
        size: 'small',
        imgSrc: './Images/pizza1.png',
    },
    {
        id: 1,
        title: 'Crispy',
        price: '475',
        size: 'medium',
        imgSrc: './Images/pizza2.png',
    },
    {
        id: 2,
        title: 'Crispy',
        price: '500',
        size: 'large',
        imgSrc: './Images/pizza3.png',
    },
    {
        id: 3,
        title: 'Stuffed',
        price: '480',
        size: 'small',
        imgSrc: './Images/pizza4.png',
    },
    {
        id: 4,
        title: 'Stuffed',
        price: '500',
        size: 'medium',
        imgSrc: './Images/pizza6.png',
    },
    {
        id: 5,
        title: 'Stuffed',
        price: '530',
        size: 'large',
        imgSrc: './Images/pizza7.png',
    },
    {
        id: 6,
        title: 'Gluten free',
        price: '380',
        size: 'small',
        imgSrc: './Images/pizza8.png',
    },
    {
        id: 7,
        title: 'Gluten free',
        price: '420',
        size: 'medium',
        imgSrc: './Images/pizza2.png',
    },
    {
        id: 8,
        title: 'Gluten free',
        price: '490',
        size: 'large',
        imgSrc: './Images/pizza3.png',
    },
]